import Head from 'next/head'
import './globals.css'
import { Quicksand } from 'next/font/google'

const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>Portfolio | Kelvin</title>
        <meta property="og:title" content="Portfolio | Kelvin" key="title" />
      </Head>
      <body className={quicksand.className}>{children}</body>
    </html>
  )
}
